### ISSUE TITLE
Speakers View - Speakers with previous sessions appear at top of list

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/mobile-android#3]
App version 4.1.3

Speakers with previous sessions are appearing at the top of the speaker list.

Example: Guy Royse is appearing at the top of the list, but was removed as a speaker since the last sync.

![Screenshot_20190710-184356](https://user-images.githubusercontent.com/5367626/61013025-a2731500-a346-11e9-9aa9-c113fef9d2b1.png)

**Comment by mdridley** [comment]
This should be fixed in 4.1.7. It was a data caching issue though, so will be hard to confirm.

**Comment by mcookWI** [comment]
I'm no longer seeing Guy at the top of the list.
