### ISSUE TITLE
Speakers detail view - Social Media icons are missing

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/mobile-android#4]
App version 4.1.3

When in the Speakers detail view, the social media icons are missing below the speaker's URL link.

These icons exist in the iOS version of the app.

Android:

![Screenshot_20190710-184851](https://user-images.githubusercontent.com/5367626/61013199-57a5cd00-a347-11e9-99a5-8645322f4d4f.png)

iOS:

![IMG_3109](https://user-images.githubusercontent.com/5367626/61013291-bbc89100-a347-11e9-8e5e-83b40224a33e.jpg)

**Comment by mdridley** [comment]
Fixed in 4.1.7
