### ISSUE TITLE
Favorites View - Selecting 'Refresh' through vertical ellipses blanks out listing

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/mobile-android#5]
App version 4.1.3

When selecting the 'Refresh' option through the vertical ellipses, the session list is blanked out. You have to go back to the calendar icon and reselect the day in order to get the list back.

**Comment by mdridley** [comment]
Fixed in 4.1.7

**Comment by mcookWI** [comment]
4.1.7 - Screen is no longer blanking out after refreshing the page.
