### ISSUE TITLE
User Profile Edit - Remove Google+ Profile URL field - G+ is no longer available

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/mobile-android#6]
App version 4.1.3

When in the screen to edit the user profile, the Google+ Profile URL field should be removed. Google+ is no longer available.

![Screenshot_20190710-194557](https://user-images.githubusercontent.com/5367626/61014214-ed435b80-a34b-11e9-9b5b-9d6d2ef24e23.png)

**Comment by mdridley** [comment]
Fixed in 4.1.7

**Comment by mcookWI** [comment]
G+ profile field has been removed.
